name: Test Composite Action

on: push

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use composite action
        uses: ./.github/action/setup-and-greet
        with:
          name: "Bala Ji"
          language: "hi"
